#!/usr/bin/env python
"""Generate `src/datarepo/_tables.py` (Arrow schemas) from the LinkML schema.

The Parquet column names, order and types are the schema's, never a second hand-written copy.
`Bundle`'s attributes name the tables; each one's range names the class whose attributes are the
columns.

    python tools/build_tables.py            # write
    python tools/build_tables.py --check    # exit 1 if the checked-in file is stale

Same contract as `tools/build_docs.py`: CI runs `--check`, so a schema edit that is not followed by
a regeneration fails the build rather than silently shipping a stale writer.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schema" / "datarepo.yaml"
STUDY_DIR = ROOT / "schema" / "study"
TARGET = ROOT / "src" / "datarepo" / "_tables.py"

# LinkML type -> the pyarrow constructor to emit. Enums and class references are foreign keys and
# identifiers, so they are strings; keeping them as strings is what lets DuckDB join them directly.
ARROW = {
    "string": "pa.string()",
    "uriorcurie": "pa.string()",
    "uri": "pa.string()",
    "integer": "pa.int64()",
    "float": "pa.float64()",
    "double": "pa.float64()",
    "decimal": "pa.float64()",
    "boolean": "pa.bool_()",
    "date": "pa.date32()",
    "datetime": "pa.timestamp('us', tz='UTC')",
}


def arrow_type(slot: dict, classes: set[str], enums: set[str]) -> str:
    rng = slot.get("range", "string")
    if rng in classes or rng in enums:
        base = "pa.string()"
    else:
        base = ARROW.get(rng)
        if base is None:
            raise SystemExit(f"build_tables: no Arrow type for LinkML range {rng!r}")
    if slot.get("multivalued"):
        return f"pa.list_({base})"
    return base


def _table_block(table: str, cls: str, classes: dict, class_names: set, enums: set) -> list[str]:
    attrs = classes[cls].get("attributes", {})
    lines = [f'    "{table}": pa.schema([  # {cls}']
    for name, attr in attrs.items():
        attr = attr or {}
        nullable = not attr.get("required", False) and not attr.get("identifier", False)
        lines.append(
            f'        pa.field("{name}", {arrow_type(attr, class_names, enums)}, '
            f"nullable={nullable}),"
        )
    lines.append("    ]),")
    return lines


def render(schema: dict, layers: dict[str, dict]) -> str:
    """Emit the core TABLES plus one STUDY_TABLES entry per study layer.

    A study layer ADDS tables keyed on core identifiers and never alters a core table (U5), so its
    tables are generated separately and the core stays usable by a consumer that is not aging. Its
    classes may reference core ones -- `Dataset`, `Sample`, `FeatureType` -- so the core's classes
    and enums are merged in for range resolution only, never for emission.
    """
    classes = schema["classes"]
    enums = set(schema.get("enums", {}))
    class_names = set(classes)

    bundle = classes["Bundle"]["attributes"]
    lines = [
        '"""Arrow schemas for the bundle tables. GENERATED by tools/build_tables.py -- do not edit."""',
        "",
        "from __future__ import annotations",
        "",
        "import pyarrow as pa",
        "",
        f'SCHEMA_VERSION = "{schema["version"]}"',
        "",
        "TABLES: dict[str, pa.Schema] = {",
    ]
    for table, slot in bundle.items():
        lines += _table_block(table, slot["range"], classes, class_names, enums)
    lines += [
        "}",
        "",
        "#: table -> the LinkML class it holds, for error messages and the bundle manifest.",
        "TABLE_CLASS: dict[str, str] = {",
    ]
    for table, slot in bundle.items():
        lines.append(f'    "{table}": "{slot["range"]}",')
    lines += ["}", ""]

    lines += [
        "#: Study layers, keyed by layer name. A study layer adds tables keyed on core identifiers",
        "#: and never alters a core table (U5), so a catalog built without one is still complete --",
        "#: these are generated separately and are not part of `TABLES`.",
        "STUDY_VERSIONS: dict[str, str] = {",
    ]
    for name, layer in sorted(layers.items()):
        lines.append(f'    "{name}": "{layer["version"]}",')
    lines += ["}", "", "STUDY_TABLES: dict[str, dict[str, pa.Schema]] = {"]
    for name, layer in sorted(layers.items()):
        merged = {**classes, **layer["classes"]}
        merged_enums = enums | set(layer.get("enums", {}))
        merged_names = set(merged)
        lines.append(f'    "{name}": {{')
        for table, slot in layer["classes"]["StudyBundle"]["attributes"].items():
            block = _table_block(table, slot["range"], merged, merged_names, merged_enums)
            lines += ["    " + line for line in block]
        lines.append("    },")
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the generated file is stale")
    args = ap.parse_args()

    schema = yaml.safe_load(SCHEMA.read_text(encoding="utf-8"))
    layers = {
        path.stem: yaml.safe_load(path.read_text(encoding="utf-8"))
        for path in sorted(STUDY_DIR.glob("*.yaml"))
    }
    text = render(schema, layers)

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is out of date; run python tools/build_tables.py")
            return 1
        print("tables up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8")
    study = sum(len(l["classes"]["StudyBundle"]["attributes"]) for l in layers.values())
    print(
        f"wrote {TARGET.relative_to(ROOT)} "
        f"({len(schema['classes']['Bundle']['attributes'])} core tables, "
        f"{study} study tables in {len(layers)} layer(s))"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
