"""Generate the schema reference pages in docs/schema/ from the LinkML schemas.

    python tools/build_docs.py          # (re)write docs/schema/*.md
    python tools/build_docs.py --check  # exit 1 if the pages are stale (CI)

The schema YAML is the single source of truth. Never edit docs/schema/*.md by hand.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from linkml_runtime.utils.schemaview import SchemaView

ROOT = Path(__file__).resolve().parents[1]
TARGETS = [
    (ROOT / "schema" / "datarepo.yaml", ROOT / "docs" / "schema" / "core.md", False),
    (ROOT / "schema" / "study" / "aging.yaml", ROOT / "docs" / "schema" / "study-aging.md", True),
]
HEADER = "<!-- GENERATED by tools/build_docs.py from {src}. Do not edit by hand. -->\n\n"


def cell(text: str | None) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def range_label(sv: SchemaView, rng: str | None) -> str:
    rng = rng or sv.schema.default_range or "string"
    if rng in sv.all_classes():
        return f"[{rng}](#{rng.lower()})"
    if rng in sv.all_enums():
        return f"[{rng}](#{rng.lower()})"
    return f"`{rng}`"


def render(src: Path, study_only: bool) -> str:
    sv = SchemaView(str(src))
    own = set(sv.all_classes(imports=False)) if study_only else set(sv.all_classes())
    own_enums = set(sv.all_enums(imports=False))
    classes = [c for c in sv.all_classes() if c in own and c != "Bundle"]

    out = [HEADER.format(src=src.relative_to(ROOT).as_posix())]
    s = sv.schema
    out.append(f"# {s.title} (v{s.version})\n\n{cell(s.description) or ''}\n\n")
    out.append(f"- **Schema id:** `{s.id}`\n- **Source:** `{src.relative_to(ROOT).as_posix()}`\n")
    if study_only:
        out.append("- **Imports:** the core schema ([core.md](core.md)). This layer only *adds* tables keyed on core IDs.\n")
    out.append("\n## Tables\n\n| Table | Grain / purpose |\n|---|---|\n")
    for c in classes:
        out.append(f"| [{c}](#{c.lower()}) | {cell(sv.get_class(c).description)} |\n")

    # Relationship diagram: an edge wherever a column's range is another table.
    edges = []
    for c in classes:
        for sl in sv.class_induced_slots(c):
            if sl.range in sv.all_classes() and sl.range != "Bundle" and not sl.identifier:
                edges.append((c, sl.range, sl.name))
    out.append("\n## How the tables connect\n\n```mermaid\nerDiagram\n")
    for a, b, name in edges:
        out.append(f'    {a} }}o--|| {b} : "{name}"\n')
    out.append("```\n")

    for c in classes:
        cd = sv.get_class(c)
        out.append(f"\n## {c}\n\n{cell(cd.description)}\n\n")
        qpx = (cd.annotations or {}).get("qpx_view")
        if qpx:
            out.append(f"QPX view: `{qpx.value}` (table-level; column mapping not yet verified).\n\n")
        out.append("| Column | Type | Req | Meaning |\n|---|---|---|---|\n")
        for sl in sv.class_induced_slots(c):
            typ = range_label(sv, sl.range) + (" [ ]" if sl.multivalued else "")
            req = "key" if sl.identifier else ("yes" if sl.required else "")
            extra = []
            if sl.pattern:
                extra.append(f"pattern `{sl.pattern}`")
            if sl.minimum_value is not None or sl.maximum_value is not None:
                extra.append(f"range {sl.minimum_value}..{sl.maximum_value}")
            meaning = cell(sl.description) + (f" ({'; '.join(extra)})" if extra else "")
            out.append(f"| `{sl.name}` | {typ} | {req} | {meaning} |\n")

    enums = [e for e in sv.all_enums() if e in own_enums]
    if enums:
        out.append("\n## Controlled vocabularies\n")
        for e in enums:
            ed = sv.get_enum(e)
            out.append(f"\n### {e}\n\n{cell(ed.description)}\n\n| Value | Meaning |\n|---|---|\n")
            for pv, pvd in ed.permissible_values.items():
                out.append(f"| `{pv}` | {cell(pvd.description)} |\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if docs are stale")
    args = ap.parse_args()
    stale = []
    for src, dst, study in TARGETS:
        text = render(src, study)
        if args.check:
            if not dst.exists() or dst.read_text(encoding="utf-8") != text:
                stale.append(dst)
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {dst.relative_to(ROOT)}")
    if stale:
        print("stale, run python tools/build_docs.py:", *[str(p.relative_to(ROOT)) for p in stale])
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
