#!/usr/bin/env python
"""Generate `src/datarepo/_tables.py` and `_schema_docs.py` from the LinkML schema.

The Parquet column names, order and types are the schema's, never a second hand-written copy.
`Bundle`'s attributes name the tables; each one's range names the class whose attributes are the
columns.

    python tools/build_tables.py            # write both
    python tools/build_tables.py --check    # exit 1 if either checked-in file is stale

`_schema_docs.py` carries the same schema's PROSE -- the table and column descriptions and the
enums' permissible values -- because `datarepo mcp`'s `describe` tool has to tell an agent what a
column means, and the Arrow schema only knows its type. It is generated for the same reason the
Arrow schemas are: a hand-kept second copy of the documentation would drift from the schema, and an
agent reading a stale description is exactly the silently-wrong answer D15 forbids.

Same contract as `tools/build_docs.py`: CI runs `--check`, so a schema edit that is not followed by
a regeneration fails the build rather than silently shipping a stale writer.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schema" / "datarepo.yaml"
STUDY_DIR = ROOT / "schema" / "study"
TARGET = ROOT / "src" / "datarepo" / "_tables.py"
DOCS_TARGET = ROOT / "src" / "datarepo" / "_schema_docs.py"

# LinkML type -> the pyarrow constructor to emit. Enums and class references are foreign keys and
# identifiers, so they are strings; keeping them as strings is what lets DuckDB join them directly.
ARROW = {
    "string": "pa.string()",
    "uriorcurie": "pa.string()",
    "uri": "pa.string()",
    "integer": "pa.int64()",
    "float": "pa.float64()",
    "double": "pa.float64()",
    "decimal": "pa.float64()",
    "boolean": "pa.bool_()",
    "date": "pa.date32()",
    "datetime": "pa.timestamp('us', tz='UTC')",
}


def arrow_type(slot: dict, classes: set[str], enums: set[str]) -> str:
    rng = slot.get("range", "string")
    if rng in classes or rng in enums:
        base = "pa.string()"
    else:
        base = ARROW.get(rng)
        if base is None:
            raise SystemExit(f"build_tables: no Arrow type for LinkML range {rng!r}")
    if slot.get("multivalued"):
        return f"pa.list_({base})"
    return base


def _table_block(table: str, cls: str, classes: dict, class_names: set, enums: set) -> list[str]:
    attrs = classes[cls].get("attributes", {})
    lines = [f'    "{table}": pa.schema([  # {cls}']
    for name, attr in attrs.items():
        attr = attr or {}
        nullable = not attr.get("required", False) and not attr.get("identifier", False)
        lines.append(
            f'        pa.field("{name}", {arrow_type(attr, class_names, enums)}, '
            f"nullable={nullable}),"
        )
    lines.append("    ]),")
    return lines


def render(schema: dict, layers: dict[str, dict]) -> str:
    """Emit the core TABLES plus one STUDY_TABLES entry per study layer.

    A study layer ADDS tables keyed on core identifiers and never alters a core table (U5), so its
    tables are generated separately and the core stays usable by a consumer that is not aging. Its
    classes may reference core ones -- `Dataset`, `Sample`, `FeatureType` -- so the core's classes
    and enums are merged in for range resolution only, never for emission.
    """
    classes = schema["classes"]
    enums = set(schema.get("enums", {}))
    class_names = set(classes)

    bundle = classes["Bundle"]["attributes"]
    lines = [
        '"""Arrow schemas for the bundle tables. GENERATED by tools/build_tables.py -- do not edit."""',
        "",
        "from __future__ import annotations",
        "",
        "import pyarrow as pa",
        "",
        f'SCHEMA_VERSION = "{schema["version"]}"',
        "",
        "TABLES: dict[str, pa.Schema] = {",
    ]
    for table, slot in bundle.items():
        lines += _table_block(table, slot["range"], classes, class_names, enums)
    lines += [
        "}",
        "",
        "#: table -> the LinkML class it holds, for error messages and the bundle manifest.",
        "TABLE_CLASS: dict[str, str] = {",
    ]
    for table, slot in bundle.items():
        lines.append(f'    "{table}": "{slot["range"]}",')
    lines += ["}", ""]

    lines += [
        "#: Study layers, keyed by layer name. A study layer adds tables keyed on core identifiers",
        "#: and never alters a core table (U5), so a catalog built without one is still complete --",
        "#: these are generated separately and are not part of `TABLES`.",
        "STUDY_VERSIONS: dict[str, str] = {",
    ]
    for name, layer in sorted(layers.items()):
        lines.append(f'    "{name}": "{layer["version"]}",')
    lines += ["}", "", "STUDY_TABLES: dict[str, dict[str, pa.Schema]] = {"]
    for name, layer in sorted(layers.items()):
        merged = {**classes, **layer["classes"]}
        merged_enums = enums | set(layer.get("enums", {}))
        merged_names = set(merged)
        lines.append(f'    "{name}": {{')
        for table, slot in layer["classes"]["StudyBundle"]["attributes"].items():
            block = _table_block(table, slot["range"], merged, merged_names, merged_enums)
            lines += ["    " + line for line in block]
        lines.append("    },")
    lines += ["}", ""]
    return "\n".join(lines)


def _py(value) -> str:
    """A Python literal for a value out of the schema. Descriptions carry quotes and newlines."""
    return repr(value)


def _one_line(text) -> str | None:
    """LinkML folds descriptions over several lines; a tool result wants one."""
    if not text:
        return None
    return " ".join(str(text).split())


def _column_docs(cls: str, classes: dict, enums: dict) -> list[str]:
    lines = []
    for name, attr in (classes[cls].get("attributes") or {}).items():
        attr = attr or {}
        rng = attr.get("range", "string")
        parts = [f'"description": {_py(_one_line(attr.get("description")))}', f'"range": {_py(rng)}']
        if rng in enums:
            parts.append(f'"enum": {_py(rng)}')
        if attr.get("identifier"):
            parts.append('"identifier": True')
        if attr.get("multivalued"):
            parts.append('"multivalued": True')
        if attr.get("unit"):
            parts.append(f'"unit": {_py(attr["unit"])}')
        lines.append(f'            "{name}": {{{", ".join(parts)}}},')
    return lines


def _table_docs(tables: dict, classes: dict, enums: dict, indent: str = "") -> list[str]:
    lines = []
    for table, slot in tables.items():
        cls = slot["range"]
        lines.append(f'    "{table}": {{')
        lines.append(f'        "class": "{cls}",')
        lines.append(f'        "description": {_py(_one_line(classes[cls].get("description")))},')
        # The slot's own description on Bundle/StudyBundle is boilerplate in this schema -- every
        # one of the 35 reads "Rows of the <table> table." -- so only the CLASS description, which
        # says what one row is, is carried. A field that says nothing costs an agent context.
        lines.append('        "columns": {')
        lines += _column_docs(cls, classes, enums)
        lines.append("        },")
        lines.append("    },")
    return [indent + line for line in lines]


def render_docs(schema: dict, layers: dict[str, dict]) -> str:
    """The schema's prose, for `datarepo mcp`'s describe tool.

    Descriptions only -- types live in `_tables.py` and are not restated here, because two
    generated copies of one fact is the drift this generator exists to prevent.
    """
    classes = schema["classes"]
    enums = schema.get("enums", {}) or {}

    lines = [
        '"""Table, column and enum documentation from the LinkML schema.',
        "",
        "GENERATED by tools/build_tables.py -- do not edit. Types are NOT here: they are in",
        "`_tables.py`, generated from the same schema, and stating them twice is how a generated",
        "file starts lying.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        f"SCHEMA_TITLE = {_py(schema.get('title') or schema.get('name'))}",
        f"SCHEMA_DESCRIPTION = {_py(_one_line(schema.get('description')))}",
        "",
        "#: Permissible values of every enum the schema declares, in the schema's own order.",
        "ENUMS: dict[str, dict[str, Any]] = {",
    ]
    for name, enum in enums.items():
        enum = enum or {}
        values = list((enum.get("permissible_values") or {}))
        lines.append(f'    "{name}": {{')
        lines.append(f'        "description": {_py(_one_line(enum.get("description")))},')
        lines.append(f'        "values": {_py(values)},')
        lines.append("    },")
    lines += ["}", "", "TABLE_DOCS: dict[str, dict[str, Any]] = {"]
    lines += _table_docs(classes["Bundle"]["attributes"], classes, enums)
    lines += ["}", "", "STUDY_TABLE_DOCS: dict[str, dict[str, dict[str, Any]]] = {"]
    for name, layer in sorted(layers.items()):
        merged = {**classes, **layer["classes"]}
        merged_enums = {**enums, **(layer.get("enums") or {})}
        lines.append(f'    "{name}": {{')
        lines += _table_docs(
            layer["classes"]["StudyBundle"]["attributes"], merged, merged_enums, indent="    "
        )
        lines.append("    },")
    lines += ["}", "", "STUDY_ENUMS: dict[str, dict[str, dict[str, Any]]] = {"]
    for name, layer in sorted(layers.items()):
        lines.append(f'    "{name}": {{')
        for enum_name, enum in (layer.get("enums") or {}).items():
            enum = enum or {}
            lines.append(f'        "{enum_name}": {{')
            lines.append(f'            "description": {_py(_one_line(enum.get("description")))},')
            lines.append(f'            "values": {_py(list(enum.get("permissible_values") or {}))},')
            lines.append("        },")
        lines.append("    },")
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if a generated file is stale")
    args = ap.parse_args()

    schema = yaml.safe_load(SCHEMA.read_text(encoding="utf-8"))
    layers = {
        path.stem: yaml.safe_load(path.read_text(encoding="utf-8"))
        for path in sorted(STUDY_DIR.glob("*.yaml"))
    }
    written = {TARGET: render(schema, layers), DOCS_TARGET: render_docs(schema, layers)}

    if args.check:
        stale = [
            target
            for target, text in written.items()
            if (target.read_text(encoding="utf-8") if target.exists() else "") != text
        ]
        for target in stale:
            print(f"{target.relative_to(ROOT)} is out of date; run python tools/build_tables.py")
        if stale:
            return 1
        print("tables up to date")
        return 0

    for target, text in written.items():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
    study = sum(len(l["classes"]["StudyBundle"]["attributes"]) for l in layers.values())
    print(
        f"wrote {TARGET.relative_to(ROOT)} and {DOCS_TARGET.name} "
        f"({len(schema['classes']['Bundle']['attributes'])} core tables, "
        f"{study} study tables in {len(layers)} layer(s), "
        f"{len(schema.get('enums') or {})} enums)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
