#!/usr/bin/env python
"""Ingest the test fixture and write `examples/ingested_bundle.yaml`.

The Arrow schemas are generated from the LinkML schema, so the ingester cannot write a column the
schema does not have. That is not the same as proving the ingester writes *valid* rows: an enum
value the schema does not permit, or a probability outside 0-1, would pass the Arrow writer and fail
LinkML.

So a real ingest is exported once, checked in, and validated by CI with `linkml-validate`. CI cannot
run the ingest itself (it needs pyMzLib's mzLib bridge), which is exactly why the committed file
matters: it is the ingester's own output, held to the published schema.

    python tools/build_example_bundle.py            # regenerate (needs pyMzLib)
    linkml-validate -s schema/datarepo.yaml -C Bundle examples/ingested_bundle.yaml

`tests/test_examples.py` regenerates and compares whenever pyMzLib is available, so the file cannot
drift away from the code unnoticed.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

TARGET = ROOT / "examples" / "ingested_bundle.yaml"

#: Rows per table. Enough to carry every column's shape without committing a large file.
LIMIT = 5

HEADER = """\
# GENERATED by tools/build_example_bundle.py -- do not edit.
#
# Real `datarepo ingest` output for the test fixture in tests/data/, trimmed to a few rows per
# table, exported as a Bundle so that LinkML validates what the ingester actually writes.
#
#   linkml-validate -s schema/datarepo.yaml -C Bundle examples/ingested_bundle.yaml
"""


def export(limit: int = LIMIT) -> dict:
    """Ingest the fixture into a temporary store and return the first rows of each table."""
    import shutil
    import tempfile

    import pyarrow.parquet as pq

    from datarepo.ingest import ingest_dataset
    from datarepo.manifest import load_manifest

    data = ROOT / "tests" / "data"
    manifest = load_manifest(data / "manifest.yaml")
    store = Path(tempfile.mkdtemp(prefix="datarepo-example-"))
    try:
        result = ingest_dataset(
            manifest,
            manifest.dataset("PXD999999"),
            store=store,
            mm_settings=data / "work_root" / "mm_settings" / "1.1.11",
        )
        bundle: dict = {}
        for path in sorted(result.bundle_path.glob("*.parquet")):
            rows = pq.read_table(path).to_pylist()[:limit]
            for row in rows:
                for key, value in list(row.items()):
                    if value is None:
                        del row[key]
                    elif hasattr(value, "isoformat"):
                        row[key] = value.isoformat()
            if rows:
                bundle[path.stem] = rows
        return bundle
    finally:
        shutil.rmtree(store, ignore_errors=True)


def render(bundle: dict) -> str:
    return HEADER + yaml.safe_dump(bundle, sort_keys=False, allow_unicode=True, width=100)


def main() -> int:
    text = render(export())
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({sum(len(v) for v in yaml.safe_load(text).values())} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
