#!/usr/bin/env python
"""Generate `src/datarepo/_tables.py` (Arrow schemas) from the LinkML schema.

The Parquet column names, order and types are the schema's, never a second hand-written copy.
`Bundle`'s attributes name the tables; each one's range names the class whose attributes are the
columns.

    python tools/build_tables.py            # write
    python tools/build_tables.py --check    # exit 1 if the checked-in file is stale

Same contract as `tools/build_docs.py`: CI runs `--check`, so a schema edit that is not followed by
a regeneration fails the build rather than silently shipping a stale writer.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schema" / "datarepo.yaml"
TARGET = ROOT / "src" / "datarepo" / "_tables.py"

# LinkML type -> the pyarrow constructor to emit. Enums and class references are foreign keys and
# identifiers, so they are strings; keeping them as strings is what lets DuckDB join them directly.
ARROW = {
    "string": "pa.string()",
    "uriorcurie": "pa.string()",
    "uri": "pa.string()",
    "integer": "pa.int64()",
    "float": "pa.float64()",
    "double": "pa.float64()",
    "decimal": "pa.float64()",
    "boolean": "pa.bool_()",
    "date": "pa.date32()",
    "datetime": "pa.timestamp('us', tz='UTC')",
}


def arrow_type(slot: dict, classes: set[str], enums: set[str]) -> str:
    rng = slot.get("range", "string")
    if rng in classes or rng in enums:
        base = "pa.string()"
    else:
        base = ARROW.get(rng)
        if base is None:
            raise SystemExit(f"build_tables: no Arrow type for LinkML range {rng!r}")
    if slot.get("multivalued"):
        return f"pa.list_({base})"
    return base


def render(schema: dict) -> str:
    classes = schema["classes"]
    enums = set(schema.get("enums", {}))
    class_names = set(classes)

    bundle = classes["Bundle"]["attributes"]
    lines = [
        '"""Arrow schemas for the bundle tables. GENERATED by tools/build_tables.py -- do not edit."""',
        "",
        "from __future__ import annotations",
        "",
        "import pyarrow as pa",
        "",
        f'SCHEMA_VERSION = "{schema["version"]}"',
        "",
        "TABLES: dict[str, pa.Schema] = {",
    ]
    for table, slot in bundle.items():
        cls = slot["range"]
        attrs = classes[cls].get("attributes", {})
        lines.append(f'    "{table}": pa.schema([  # {cls}')
        for name, attr in attrs.items():
            attr = attr or {}
            nullable = not attr.get("required", False) and not attr.get("identifier", False)
            lines.append(
                f'        pa.field("{name}", {arrow_type(attr, class_names, enums)}, '
                f"nullable={nullable}),"
            )
        lines.append("    ]),")
    lines += [
        "}",
        "",
        "#: table -> the LinkML class it holds, for error messages and the bundle manifest.",
        "TABLE_CLASS: dict[str, str] = {",
    ]
    for table, slot in bundle.items():
        lines.append(f'    "{table}": "{slot["range"]}",')
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the generated file is stale")
    args = ap.parse_args()

    schema = yaml.safe_load(SCHEMA.read_text(encoding="utf-8"))
    text = render(schema)

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is out of date; run python tools/build_tables.py")
            return 1
        print("tables up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(schema['classes']['Bundle']['attributes'])} tables)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
